name: Publish Docker image

on:
  push:
    branches:
      - main
      - master
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for main image
        id: meta
        uses: docker/metadata-action@e1a45f6e54773201956dae54cd74ee7fdcafe877
        with:
          images: cyberpearuk/nginx-proxy
          tags: |
            type=raw,event=tag,value=${{ env.TAG }}
            type=raw,event=branch,value=latest,enable={{is_default_branch}}
      - name: Build and push main image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: production
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: Extract metadata (tags, labels) for nginx only image
        id: nginx-base-meta
        uses: docker/metadata-action@e1a45f6e54773201956dae54cd74ee7fdcafe877
        with:
          images: cyberpearuk/nginx
          tags: 
            type=raw,event=tag,value=${{ env.TAG }}
            type=raw,event=branch,value=latest,enable={{is_default_branch}}
      - name: Build and push nginx only image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: nginx-base
          tags: ${{ steps.nginx-base-meta.outputs.tags }}
          labels: ${{ steps.nginx-base-meta.outputs.labels }}
